### ISSUE TITLE
添加多于4个控制器崩溃

### ISSUE THREAD

**Issue by RondaHo** [agdsdl/DLSlideView#1]
你代码里有一句断言，限定了最多4个控制器。希望可以设计成无限个，像网易新闻那样。
DLTabedSlideView设计成scrollView，再加入可以设置item距离和每个item尺寸的属性，这样就完美了。
你每个item后面跟一个图标的设计挺不错的，这样比纯文字的item生动了许多。

**Comment by agdsdl** [comment]
目前项目中的需求是标签个数2~4个不等，每个item均分view的宽度，不需要滚屏。因此目前就是这样实现的。
不过代码中预留了相应接口，只需要实现DLSlideTabbarProtocol就可以自定义标签页，而且参考现有的DLImagedTabbarView实现一个可滚动的标签页也是很容易的。
说起来不难可是要将效果优化好还需要花点时间，这个等后面再做。

**Comment by RondaHe** [comment]
期待...

**Comment by agdsdl** [comment]
新春福利！搞定了，无限页面，可滚动tabbar...
