### ISSUE TITLE
storyboard version

### ISSUE THREAD

**Issue by dreamgo** [agdsdl/DLSlideView#2]
Hi there,
Thanks for your great job. I met some problems when I add your library into my app which build with storyboard. Subviews seem be loaded front the consle log but not visible. I can't find the reason. Any idea about that ? If you could help release a storyboard version you'll be very appreciated.

Thanks.

**Comment by agdsdl** [comment]
storyboard demo added.

**Comment by dreamgo** [comment]
Appreciate!
