### ISSUE TITLE
uitableview 的 scrolltotop失效

### ISSUE THREAD

**Issue by a289459798** [agdsdl/DLSlideView#21]
就算只有一个viewcontroller，uitableview的返回顶部功能也会失效

**Comment by agdsdl** [comment]
页面里同时有多个scrollview的时候，scrollTop会失效。
解决办法是把其他scrollview（slidetabbar）的scrollToTop属性设为false。

**Comment by a289459798** [comment]
用的dlslideview，只有一个viewcontroller，而且也只有一个uitableview

**Comment by a289459798** [comment]
我想问一下我能不能禁掉dlslideview 的 滑动切换视图效果？

**Comment by agdsdl** [comment]
没有现成接口，你需要自己改代码

**Comment by a289459798** [comment]
怎么改呢？
