### ISSUE TITLE
在使用过程中发现以下问题

### ISSUE THREAD

**Issue by Engandend** [agdsdl/DLSlideView#28]
用 DLCustomSlideView 初始化的前提
1、用手势滚动到非第一个viewController的时候，  取当前的selectIndex 不正确
2、如果添加了多个viewCOntroller  在 初始化的那个viewController中用  self.childViewControllers 取值，发现只有数组里面只有第一个viewController   不知道是不是我的打开方式不对

**Comment by agdsdl** [comment]
1. 先debug，如果还有问题，贴出相关代码
2. 是这样的，childviewcontrolls里面只维护当前显示的viewcontroller

**Comment by Engandend** [comment]
初始化
`-(void)setSlideView
{
    if (self.slideView) {
        return;
    }
    self.slideView = [[DLCustomSlideView alloc]initWithFrame:CGRectMake(0, _headInfoView.bottom, SCREEN_WIDTH, SCREEN_HEIGHT - _headInfoView.bottom - [JQAcutionLiveDetailBottomView getHeight])];
    [self.view addSubview:self.slideView];
    self.slideView.delegate = self;
    
    DLLRUCache *cache = [[DLLRUCache alloc] initWithCount:6];
    DLScrollTabbarView *tabbar = [[DLScrollTabbarView alloc] initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, 35)];
    tabbar.tabItemNormalColor = [UIColor blackColor];
    tabbar.backgroundColor = [UIColor whiteColor];
    tabbar.tabItemSelectedColor = MAINCOLOR2;
    tabbar.tabItemNormalFontSize = 15.0f;
    tabbar.trackColor = MAINCOLOR2;
    itemArray_ = [NSMutableArray array];
    
    
    NSArray *titleArr = @[@"拍品详情",
                          @"聊天室",
                          @"出价记录"];
    
    for (NSInteger i = 0; i < titleArr.count; i ++) {
        DLScrollTabbarItem *item = [DLScrollTabbarItem itemWithTitle:titleArr[i] width:SCREEN_WIDTH/titleArr.count];
        [itemArray_ addObject:item];
    }
    
    tabbar.tabbarItems = itemArray_;
    
    self.slideView.tabbar = tabbar;
    self.slideView.cache = cache;
    self.slideView.tabbarBottomSpacing = 0;
    self.slideView.baseViewController = self;
    [self.slideView setup];
    self.slideView.selectedIndex = 0;
}`


delegate
`- (NSInteger)numberOfTabsInDLCustomSlideView:(DLCustomSlideView *)sender{
    return itemArray_.count;
}

- (UIViewController *)DLCustomSlideView:(DLCustomSlideView *)sender controllerAt:(NSInteger)index{
    
    
    if (index == 0) {
        _liveDetailVC = [[JQLiveDetailViewController alloc] init];
        _liveDetailVC.frameHeigh = self.slideView.height - self.slideView.tabbar.height;
        _liveDetailVC.model = _model;
        return _liveDetailVC;
    }
    else if (index == 1)
    {
        _liveCommentVC = [[JQLiveCommentViewController alloc] init];
        _liveCommentVC.frameHeigh = self.slideView.height - self.slideView.tabbar.height;
        _liveCommentVC.model = _model;
        return _liveCommentVC;
    }else{
        _liveRecordVC = [[JQLiveRecordViewController alloc] init];
        _liveRecordVC.frameHeigh = self.slideView.height - self.slideView.tabbar.height;
        _liveRecordVC.model = _model;
        return _liveRecordVC;
    }
}`



获取当前选中的selectIndex
NSLog(@"self.slideView.selectedIndex = %ld",self.slideView.selectedIndex);

发现无论是在滑动改变VC  还是通过点击按钮改变VC  最后得到的结果都是0
只有在手动设置self.slideView.selectedIndex = 1;  在此打印的时候才能得到1

我认为：在你的代码内部，你并没有对 selectIndex 做更新
