### ISSUE TITLE
need lazyLoading support

### ISSUE THREAD

**Issue by RondaHo** [agdsdl/DLSlideView#3]
您好，作者，我又来了，嘻嘻。
感谢你开源这么方便强大的一个库。加上了无限循环页面，也做了内存优化。
我在使用中发现貌似没有懒加载模式，当一个页面开始出现一点点时就会调用ViewdidLoad开始加载。而不是等到停止滑动时才开始加载。如果有很多个页面，像网易新闻一样，每个页面都有很多新闻数据，从第一个页面依次滑动到最后一个页面，那会把所有的页面都加载出来，感觉不是太好。

**Comment by agdsdl** [comment]
这应该是bug，已经修正。现在可以在viewDidAppear中实现懒加载。
