### ISSUE TITLE
Probably need DLTabedSlideView willSelectedAt

### ISSUE THREAD

**Issue by steve21124** [agdsdl/DLSlideView#30]
Probably need DLTabedSlideView willSelectedAt: 
- (void)DLTabedSlideView:(DLTabedSlideView *)sender willSelectedAt:(NSInteger)index;
or
- (UIViewController *)DLTabedSlideView:(DLTabedSlideView *)sender controllerAt:(NSInteger)index => need to behave like viewForItemAtIndex
because there are times before displaying view controller customization need to be done

**Comment by agdsdl** [comment]
Why not using the "viewWillAppear" of your "view controller"?

**Comment by steve21124** [comment]
thanks. I think the issues might be specific for my needs. I use it in my fork version
