### ISSUE TITLE
打包接入unity之后，unity导出xcode工程能编译通过，链接出错如下DLTabedbarItem Objc-class-ref not found for architecture arm64

### ISSUE THREAD

**Issue by hopesala** [agdsdl/DLSlideView#31]
这个问题已经解决，但遇到如下链接出错问题

**Comment by agdsdl** [comment]
不太明白你的意思，一般解决被UINavigationBar遮挡采用的方法是设置inset。
scrollview的话用automaticallyAdjustsScrollViewInsets

**Comment by hopesala** [comment]
![image](https://cloud.githubusercontent.com/assets/8850257/26272330/04aeee9a-3d48-11e7-960d-f714018fed73.png)
我对DLSlideView的样式做了一些调整，现在的问题是，我添加的UINavigationBar里的返回和右上角的按钮点了都没反应，添加断点也不能捕获

**Comment by hopesala** [comment]
![image](https://cloud.githubusercontent.com/assets/8850257/26275512/dc19be18-3d94-11e7-85c6-72cf8a71e2b6.png)
打包接入unity，unity导出的ios项目工程在xcode里打开报这个错误，请问是我配置的哪个地方有错误吗

**Comment by agdsdl** [comment]
这是打包缺少arm64库，检查你的编译选项。类似的问题可以问谷歌。

**Comment by hopesala** [comment]
好的，谢谢您！
