### ISSUE TITLE
Bar快速点击异常

### ISSUE THREAD

**Issue by xiaoyishan** [agdsdl/DLSlideView#34]
点击Bar时 当切换过快时 在动画未结束时点击无效 2个demo都存在

**Comment by agdsdl** [comment]
是的，这是处理是为了保护内部状态。

**Comment by xiaoyishan** [comment]
你修复一下吧…… 本来想直接用你的代码 后面我自己写了一个




发自网易邮箱大师
在2017年07月27日 09:47，agdsdl 写道：

是的，这是处理是为了保护内部状态。
