### ISSUE TITLE
创建超过4个的子页面 出现的问题 

### ISSUE THREAD

**Issue by zejun-huang** [agdsdl/DLSlideView#37]
当我创建4个以上的页面时  ，按照您的demo的方法写了一遍   报错 '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'  我 不知道 那个数组 传了空值  。

**Comment by yanngxinlei** [comment]
我也是遇到了这个问题，很头疼，还不知道那里出错了

**Comment by yanngxinlei** [comment]
_tabedSlideView.delegate = self;  设置这个好了

**Comment by agdsdl** [comment]
👍
