### ISSUE TITLE
你好 UISlider跟库冲突的问题，我看了下文章 还不知道怎么整

### ISSUE THREAD

**Issue by huxiaoxin** [agdsdl/DLSlideView#43]
重写了touchesShouldBegin，滑动UIScrollView上的任何元素这个函数会立刻向UIScrollView报告，所以在这个时候判断如果是UISlider就把Scroll禁止掉。
init中注册了一个通知，用来监听在slider放开的时候让Scroll可以重新滚动，这个消息由slider的两个点击释放 ，这个只需要写一个UIScrollView的类扩展就行了吗

**Comment by huxiaoxin** [comment]
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
    
    
    /*
     直接拖动UISlider，此时touch时间在150ms以内，UIScrollView会认为是拖动自己，从而拦截了event，导致UISlider接受不到滑动的event。但是只要按住UISlider一会再拖动，此时此时touch时间超过150ms，因此滑动的event会发送到UISlider上。
     */
    UIView *view = [super hitTest:point withEvent:event];
    
    if([view isKindOfClass:[UISlider class]])
    {
        //如果响应view是UISlider,则scrollview禁止滑动
        self.scrollEnabled = NO;
    }
    else
    {   //如果不是,则恢复滑动
        self.scrollEnabled = YES;
    }
    return view;
}这样写没效果

**Comment by agdsdl** [comment]
没看懂

**Comment by huxiaoxin** [comment]
就是我刚刚在你的DLSlideView类里吧panHandler 这个手势方方法给注释掉，然后滑动slider正常，但是不能切换子控制器了。
![snip20180327_1](https://user-images.githubusercontent.com/28379471/37950986-5360681e-31cd-11e8-8fff-734b8fe3de39.png)

**Comment by agdsdl** [comment]
UISlide的滑动没必要重写什么，直接用就是了

**Comment by huxiaoxin** [comment]
已经解决了 在那个DLSlideView类里的手势的代理方法里禁止掉滑动手势
