### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JohnnyHooo** [agdsdl/DLSlideView#5]
6p 和 ip6 上面快速左右滑动的时候(不滑到别的视图) 第二个视图会停留在当前视图上

**Comment by agdsdl** [comment]
是点击标签页快速切换吗？

**Comment by JohnnyHooo** [comment]
快速在vc切换标签,就会发生, 仔细看了下是所有设备都会这样.  
操作如下:
VC1 向左滑转到 VC2  大概滑到一半的时候快速右滑(滑出屏幕),  就能看到BUG了.

**Comment by JohnnyHooo** [comment]
![e07bfdb0-8178-4204-bbbb-17252b7e72d2](https://cloud.githubusercontent.com/assets/7742370/6701070/8713a3de-cd52-11e4-923b-9b8b852683c4.png)
如图 蓝色是页面0的  紫色是页面1的.

**Comment by agdsdl** [comment]
谢谢反馈，bug已经解决~

**Comment by JohnnyHooo** [comment]
T T才解决,我都已经换别的了. 我预留了你的接口N久了,最后上架了,没办法就删了

**Comment by agdsdl** [comment]
Sorry to hear that...最近太忙了...抱歉了...
