### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by roshanman** [agdsdl/DLSlideView#7]
当viewcontroller非常多的时候，没有重用机制啊。希望能添加类似tableview的dequeue的方式。
没有reload接口，无法动态增删viewcontroller。

**Comment by leo90821** [comment]
如果纯代码创建怎么使用？不用xib和storyboard作为界面。（如果直接复制你demo1 的代码，TabedSlideView 为空，不能创建，如果直接创建则会报错，请问如何解决）

**Comment by agdsdl** [comment]
@Jameson-zxm DLCache内建缓存和重用。你可以通过实现DLCacheProtocol协议来实现自己的重用逻辑。

**Comment by agdsdl** [comment]
@leo90821 alloc一个TabedSlideView，记得设置他的delegate属性。
我讲delegate属性的设置防止nib文件中了，所以你要在代码里加上这个设置。
