### ISSUE TITLE
无法滑动切换view controller

### ISSUE THREAD

**Issue by BluesZhang** [agdsdl/DLSlideView#8]
如果在view controller中加入一个webview，webview本身需要支持放大缩小功能。在网页未放大时，切换vc都是正常的；但如果页面放大以后，就无法切换vc了

**Comment by agdsdl** [comment]
这是由于webview本身的scrollview拦截了滑动事件，slideview获取不到滑动事件。
这个问题，估计得在webview上解决。

**Comment by wubangshun** [comment]
抽离出来，加UINavigationController 和 UITabarController 就会出现问题，菜单没法正常显示，可以上下滚动了！  但是在你Demo中加加UINavigationController 和 UITabarController 就正常！ 这是为什么呢？

**Comment by agdsdl** [comment]
@wubangshun 这个得看你具体代码了，我们在项目使用中是没有问题的。

**Comment by wubangshun** [comment]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    ViewController *ctrl = [[ViewController alloc] initWithNibName:@"ViewController" bundle:nil];
    // 添加 TabBar 就有问题 ，Demo2 滑动时，菜单会往上跑
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:ctrl];
    UITabBarController *tabbar = [[UITabBarController alloc]init];
    [tabbar addChildViewController:nav];
    self.window.rootViewController = tabbar;
    
    [self.window makeKeyAndVisible];
    return YES;
}

**Comment by wubangshun** [comment]
```
(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
ViewController *ctrl = [[ViewController alloc] initWithNibName:@"ViewController" bundle:nil];
// 添加 TabBar 就有问题 ，Demo2 滑动时，菜单会往上跑
UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:ctrl];
UITabBarController *tabbar = [[UITabBarController alloc]init];
[tabbar addChildViewController:nav];
self.window.rootViewController = tabbar;

[self.window makeKeyAndVisible];
return YES;
}
```

这是直接在你Demo中添加的，你有时间试试。

**Comment by agdsdl** [comment]
在你的viewController中添加“    self.automaticallyAdjustsScrollViewInsets = NO;”可以解决这个问题。
