### ISSUE TITLE
滑动与tableview 的滑动删除冲突

### ISSUE THREAD

**Issue by a289459798** [agdsdl/DLSlideView#9]
怎么解决tableview 滑动删除失效？

**Comment by agdsdl** [comment]
要不你改下代码，禁用DLSlideView的滑动功能😓

**Comment by a289459798** [comment]
有开关吗？能不能判断滑动cell的时候关闭，否则打开？

**Comment by agdsdl** [comment]
那你得自己写cell滑动功能，兄弟。在cell里嵌入一个scrollview就可以拦截到滑动事件了，然后自己处理滑动删除动作。

**Comment by duckls** [comment]
1.滑动手势与我侧滑左菜单栏手势冲突。侧滑菜单栏 用的是  'RESideMenu', '4.0.7'。
2.放在首页有导航控制器 和tabbar 所以视图需要减去这部分的高度 。我减去了这部分高度。。但是在控制器里面加入View.使其等于self.View.frame 。 frame 不对。 写在viewDidAppear 这里面是可以的  。
求解决办法？
没看到 issues 可以发截图 。 如果看不懂我描述的，可以qq 联系 358591449 ？ 谢谢作者的贡献。

**Comment by agdsdl** [comment]
确实没看懂。
第一点请参考之前的回复。
第二点请参考demo

**Comment by duckls** [comment]
@agdsdl  已经解决 感谢
